### ISSUE TITLE
Peer to Peer Code Review February 10th

### ISSUE THREAD

**Issue by DavidEspinoG** [getssh/web-course-capstone#1]
# Excellent job, Getayawkal! 
You've done a nice job, however, there are some improvements you could make in order to make your code even better. 
- It would be great to add the gray social media bar in order to follow the design guidelines. 🧑🏽‍🎨
- Be sure that the about link is working properly, that would improve the user experience ☺️
- Reducing the empty unnecessary empty spaces in the "partners" section would improve the look of the website and the user experience. 🧑🏽‍💻

**Comment by getssh** [comment]
Thank you for your feedback.
I have worked on those issues 
- Added the social bar at the top
- About link at the top now working 
- I reduced the space at the partner's section
